# FCOS with improvements
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: None #"catalog://ImageNetPretrained/MSRA/R-50"
  #WEIGHT: "FCOS_imprv_R_50_FPN_1x.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    # positioning centerness on the regress branch.
    # Please refer to https://github.com/tianzhi0549/FCOS/issues/89#issuecomment-516877042
    CENTERNESS_ON_REG: True
    # using center sampling and GIoU.
    # Please refer to https://github.com/yqyao/FCOS_PLUS
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("coco_2014_minival",)
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  TYPE: 'SGD' #SGD, RAdam
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  MAX_ITER: 360000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
#export CUDA_VISIBLE_DEVICES=0 && python tools/train_net.py --config-file configs/fcos/fcos_imprv_R_50_FPN_1x_coco.yaml --logdir ./logs/ --exp_name COCO_v2 DATALOADER.NUM_WORKERS 0 OUTPUT_DIR training_dir/fcos_imprv_R_50_FPN_1x_coco_scratch

